openapi: 3.0.3
info:
  title: ReferralAPI
  version: 0.0.0
  description: RESTful API сервис для реферальной системы
paths:
  /api/token/:
    post:
      operationId: api_token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/token/refresh/:
    post:
      operationId: api_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /referral/all/:
    get:
      operationId: referral_all_list
      description: Concrete view for listing a queryset.
      tags:
      - referral
      security:
      - basicAuth: []
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Referral'
          description: ''
  /referral/create/:
    post:
      operationId: referral_create_create
      description: Concrete view for creating a model instance.
      tags:
      - referral
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Referral'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Referral'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Referral'
        required: true
      security:
      - basicAuth: []
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Referral'
          description: ''
  /referral/delete/:
    delete:
      operationId: referral_delete_destroy
      description: Concrete view for deleting a model instance.
      summary: delete users actual referral code
      tags:
      - referral
      security:
      - basicAuth: []
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /user/all/:
    get:
      operationId: user_all_list
      description: |-
        A viewset that provides default asynchronous `create()`, `retrieve()`, `update()`,
        `partial_update()`, `destroy()` and `list()` actions.
      summary: List of users
      tags:
      - user
      security:
      - basicAuth: []
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/aUserView'
          description: ''
  /user/all/{id}/:
    get:
      operationId: user_all_retrieve
      description: |-
        A viewset that provides default asynchronous `create()`, `retrieve()`, `update()`,
        `partial_update()`, `destroy()` and `list()` actions.
      summary: User detail
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - user
      security:
      - basicAuth: []
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/aUserView'
          description: ''
  /user/referral/get/:
    get:
      operationId: user_referral_get_retrieve
      summary: Actual users referral to email
      tags:
      - user
      security:
      - basicAuth: []
      - cookieAuth: []
      - jwtAuth: []
      responses:
        '200':
          description: No response body
  /user/referrals/{id}/:
    get:
      operationId: user_referrals_retrieve
      summary: List of invited users
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - user
      security:
      - basicAuth: []
      - cookieAuth: []
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/aUserView'
          description: ''
  /user/register/:
    post:
      operationId: user_register_create
      summary: New user
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/aUserCreate'
            examples:
              PostExample:
                value:
                  username: testuser_xxx
                  email: user@example.com
                  password: string
                summary: Post example
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/aUserCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/aUserCreate'
        required: true
      security:
      - basicAuth: []
      - cookieAuth: []
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/aUserCreate'
          description: ''
  /user/register/{ref_code}/:
    post:
      operationId: user_register_create_with_referral_code
      summary: New user
      parameters:
      - in: path
        name: ref_code
        schema:
          type: string
        required: true
      tags:
      - user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/aUserCreate'
            examples:
              PostExample:
                value:
                  username: testuser_xxx
                  email: user@example.com
                  password: string
                summary: Post example
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/aUserCreate'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/aUserCreate'
        required: true
      security:
      - basicAuth: []
      - cookieAuth: []
      - jwtAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/aUserCreate'
          description: ''
components:
  schemas:
    Referral:
      type: object
      description: Base serializer class.
      properties:
        id:
          type: integer
          readOnly: true
        create_date:
          type: string
          format: date
          readOnly: true
          title: Дата создания
        code:
          type: string
          title: Реферальный код
          maxLength: 100
        valid_period:
          type: integer
          title: Срок действия
        end_date:
          type: string
          format: date
          title: Дата окончания
        owner:
          type: integer
          title: Владелец
      required:
      - code
      - create_date
      - end_date
      - id
      - owner
      - valid_period
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
    aRefCode:
      type: object
      description: Base serializer class.
      properties:
        code:
          type: string
          title: Реферальный код
          maxLength: 100
      required:
      - code
    aUserCreate:
      type: object
      description: Base serializer class.
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        password:
          type: string
          maxLength: 128
        referrer:
          type: integer
          nullable: true
          title: Реферер
      required:
      - password
      - username
    aUserView:
      type: object
      description: Base serializer class.
      properties:
        id:
          type: integer
          readOnly: true
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          title: Email address
          maxLength: 254
        groups:
          type: array
          items:
            type: integer
          description: The groups this user belongs to. A user will get all permissions
            granted to each of their groups.
        referrer:
          type: integer
          nullable: true
          title: Реферер
        referral_code:
          $ref: '#/components/schemas/aRefCode'
      required:
      - id
      - referral_code
      - username
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
