# Generated by Django 4.2 on 2025-03-07 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_created=True, auto_now=True, verbose_name='Дата создания')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Реферальный код')),
                ('valid_period', models.IntegerField(verbose_name='Срок действия')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Реферал')),
            ],
        ),
    ]
